# Математика для машинного обучения
## Домашнее задание №4

_Автор задания: Илья Щуров_

Подготовлено для программы «[Практический анализ данных и машинное обучение](https://cs.hse.ru/dpo/bigml)» (ФКН НИУ ВШЭ).

Задание выполнил(а): *(впишите сюда фамилию и имя)*

### О задании

В задании встречаются задачи трёх видов. Обычные задачи — чаще всего, простые задачи на определения. Их нужно сделать, если понятия, обсуждавшиеся на лекции, кажутся вам новыми или прочно забытыми. Задачи со звёздочкой — на доказательства. Их можно пропустить, если вы проходите этот материал впервые, но они помогут разобраться в нём глубже. Они также не являются сложными при наличии некоторой математической подготовки. Наконец, задачи с двумя звёздочками — для тех, кто имеет математическое образование.

Вы можете выбрать, какой тип задач вы хотите решать — скорее всего, если вы можете решить задачи со звёздочкой, то задачи без звёздочек будут для вас слишком простыми (но может быть и нет — в любом случае, просмотрите их и поймите, являются ли они для вас совсем устными; если нет — лучше сделайте их).

### Задача 1
Рассмотрим уравнение
$$2x_1 + 3x_2 - 5x_3 = 0.$$

Оно задаёт некоторую плоскость. Найти координаты двух линейно независимых векторов, лежащих в этой плоскости.

**Подсказка.** Искомые векторы можно найти в виде $(x_1^1, 1, 0)$ и $(x_1^2, 0, 1)$ (верхний индекс — это номер вектора, а не степень). Докажите, что любые такие векторы линейно независимы (какими бы ни были $x_1^1$ и $x_1^2$). Найдите $x_1^1$ и $x_1^2$ из уравнения.

*(впишите решение сюда)*

### Задача 2

Рассмотрим систему уравнений

$$\begin{cases}
x_1 - 2x_2 + x_3 = 0 \\
2x_1 + 3x_2 - 5x_3 = 0
\end{cases}$$

Показать, что система задаёт некоторую прямую и задать её в параметрическом виде.

**Подсказка.** Выразить $x_1$ и $x_2$ через $x_3$, затем найти вектор вида $(x_1, x_2, 1)$, лежащий на этой прямой.

*(впишите решение сюда)*

### Задача 3
Рассмотрим систему уравнений

$$\begin{cases}
x_1 + 2x_2 + x_3 + x_4 = 0 \\
2x_1 + 3x_2 - 5x_3 - x_4 = 0
\end{cases}$$

Показать, что система задаёт некоторую двумерную плоскость и найти координаты двух линейно незвисимых векторов, лежащих в этой плоскости.

**Подсказка.** Искомые векторы можно найти в виде $(x_1^1, x_2^1, 1, 0)$ и $(x_1^2, x_2^2, 0, 1)$.

*(впишите решение сюда)*

**Определение**

*Линейным подпространством* $V \subset \mathbb R^n$ называется такое подмножество векторов, что для любых $u, v\in V$ и любого скаляра $\lambda \in \mathbb R$:

- $u + v \in V$;
- $\lambda u \in V$.

*Аффинным подпространством* $W \subset \mathbb R^n$  множество векторов $\{u_0 + v \mid v \in  V\}$, получаемых из некоторого фиксированного вектора $u_0$ прибавлением всевозможных векторов из линейного подпространства $V$. Иными словами, аффинное подпространство — это результат сдвига линейного подпространства на некоторый фиксированный вектор.

### Задача 4
Является ли линейным подпространством множество векторов $(x_1, x_2, x_3)\in \mathbb R^3$, заданное следующим образом (каждое условие — отдельный пункт):

1. $x_1=0$;
1. $x_1^2 + x_2 + x_3 = 0$ (здесь $x_1^2$ — это $x_1$ в квадрате);
2. $x_1 + x_2 + x_3 = 1$;
3. $x_1=0$ или $x_2=0$.

### Задача 5 (*)
Доказать, что для любой прямоугольной матрицы $A$ множество всех решений системы $Ax=0$ является линейным подпространством (если оно непусто, то есть если хоть какие-то решения у системы есть), а множество всех решений системы $Ax=b$ является аффинным подпространством. Как связаны решения этих двух систем?

*(впишите решение сюда)*

### Задача 6

Докажите, что $(AB)^T=B^T A^T$ для любых матриц $A$, $B$, таких, что определено произведение $AB$. Здесь $X^T$ — транспонированная матрица $X$.

*(впишите решение сюда)*

### Задача 7
Рассмотрим *диагональную* матрицу 
$$D=D(\lambda_1, \lambda_2, \ldots, \lambda_n) = 
\begin{pmatrix}
\lambda_1 & 0& \ldots& 0\\
0& \lambda_2& \ldots &0\\
\vdots & \vdots & \ddots & \vdots \\
0& 0&\ldots &\lambda_n
\end{pmatrix}.
$$
(На диагонали — числа $\lambda_1,\lambda_2, \ldots, \lambda_n$, все остальные компоненты нулевые.)

Рассмотрим произвольную матрицу $A$ подходящего размера (такого, чтобы соответствующие произведения были определены).

1. Как связаны матрицы $A$ и $DA$?
2. Как связаны матрицы $A$ и $AD$?

*(впишите решение сюда)*

### Задача 8
С помощью `numpy` найти произведение матриц

$$
A = \begin{pmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8
\end{pmatrix}
$$

и 

$$B = \begin{pmatrix}
4 & 2 & 1 \\
3 & 5 & 7 \\
1 & 9 & 2 \\
2 & 4 & 1
\end{pmatrix}$$

в том порядке, в котором это произведение определено. Что будет, если попытаться посчитать произведение в другом порядке?

*(впишите решение сюда)*

### Задача 9 (*)

Дан вектор $v\in \mathbb R^n$ (в виде одномерного `np.array`). Требуется написать программу, строящую матрицу, строками которой являются векторы $t v$ для $t = -1 + k/10,\ k = 0, \ldots, 20$ (то есть $t$ пробегает значения от $-1$ до $1$ с шагом $1/10$, всего $21$ значение). Получающаяся матрица должна иметь $21$ строку и $n$ столбцов. 

**Подсказка.** Для решения задачи вам нужно использовать матричное умножение, а для этого придётся делать из векторов матрицы (вектор-столбцы или вектор-строки). Это можно сделать, например, так:

In [53]:
import numpy as np
v = np.array([1, 3, 10, 3])
v # это просто вектор

array([ 1,  3, 10,  3])

In [74]:
v.T # он не меняется при транспонировании

array([ 1,  3, 10,  3])

In [68]:
v_column = v[:, np.newaxis]
v_column # это вектор-столбец

array([[ 1],
       [ 3],
       [10],
       [ 3]])

In [69]:
v_row = v[np.newaxis, :]
v_row # это вектор-строка

array([[ 1,  3, 10,  3]])

In [1]:
# ваше решение здесь

### Задача 10 (**)
*Рангом* матрицы называется максимальное число её линейно независимых строк или максимальное число её линейно независимых столбцов (можно доказать, что оба числа обязательно совпадают).

Матрицы с малым рангом важны в задачах машинного обучения.

Пусть известно, что прямоугольная матрица $A$ имеет ранг $k$. Доказать, что можно выбрать $k$ строк и $k$ столбцов этой матрицы, таких, что по ним она однозначно восстанавливается. Найти явную формулу для такого восстановления. (Для решения этой задачи вам понадобится понятие обратной матрицы.)

*(впишите решение сюда)*